### ISSUE TITLE
Can't deregister files using beagle cli with most recent develop branch

### ISSUE THREAD

**Issue by allanbolipata** [mskcc/beagle#316]
I suspect the changes to the queries broke this. Now returns error

```
Traceback (most recent call last):
  File "deregister_jobs_and_files.py", line 59, in <module>
    FETCH_SAMPLE_JOBS = get_jobs(REQUEST_ID)
  File "deregister_jobs_and_files.py", line 19, in get_jobs
    data = BEAGLE.get_etl_jobs_by_request(request_id)['results']
  File "/home/bolipatc/beagle_cli/scripts/bin/access_beagle_endpoint.py", line 23, in get_etl_jobs_by_request
    return self.run_url(url)
  File "/home/bolipatc/beagle_cli/scripts/bin/access_beagle_endpoint.py", line 18, in run_url
    return req.json()
  File "/home/bolipatc/beagle_cli/venv/lib/python3.7/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/opt/common/CentOS_7/python/python-3.7.1/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/opt/common/CentOS_7/python/python-3.7.1/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/common/CentOS_7/python/python-3.7.1/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
```

If I go back to an older version of `beagle`, it works. What changed? Without this it makes it difficult to remove records for debugging/testing the entire JIRA integration starting from import. @sivkovic @nikhil

**Comment by allanbolipata** [comment]
I restarted the server a couple times and it worked again. Not sure if I can replicate it now.

Leaving this open for the time being.
