### ISSUE TITLE
Implement connection pooling

### ISSUE THREAD

**Issue by ionox0** [mskcc/beagle#647]
On attempting to start 6 ACCESS runs, totaling a few hundred samples, the following error appeared in the logs

I believe this can be resolved by either raising the posgres `max_connections` or `CONN_MAX_AGE` settings, or using connection pooling with `pgbouncer` https://www.compose.com/articles/how-to-pool-postgresql-connections-with-pgbouncer/

It might also be possible to just find the spot in the code where these runs get submitted, and add some sort of delay to prevent all of the jobs statuses being saved in the DB at the same time, if it's overly complicated to deal with a separate connection pool 

For now it also might just be fine to just be aware of this limitation, and not try to submit so many runs at the same time, just wanted to get some feedback about whether I should look into any of these solutions. 

Error from `ridgeback_worker.log`:
```
[2020-12-24 11:37:26,770: INFO/ForkPoolWorker-7] Task toil_orchestrator.tasks.submit_jobs_to_lsf[3370d5ed-c135-4444-ad1a-456d50a8e5cd] succeeded in 0.6690826863050461s: None
[2020-12-24 11:37:26,773: ERROR/ForkPoolWorker-10] Job Saved
[2020-12-24 11:37:26,774: ERROR/ForkPoolWorker-10] Task toil_orchestrator.tasks.submit_jobs_to_lsf[6670ac63-81f1-4e4f-96a1-0afe9bc8b871] raised unexpected: OperationalError('FATAL:  remaining connection slots are reserved for non-replication superuser connections\n')
Traceback (most recent call last):
  File "/juno/work/ci/prod_ridgeback/venv/lib/python3.7/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/juno/work/ci/prod_ridgeback/venv/lib/python3.7/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/juno/work/ci/prod_ridgeback/venv/lib/python3.7/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/juno/work/ci/prod_ridgeback/venv/lib/python3.7/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  remaining connection slots are reserved for non-replication superuser connections


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/juno/work/ci/prod_ridgeback/venv/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/juno/work/ci/prod_ridgeback/venv/lib/python3.7/site-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/srv/services/voyager/ridgeback/toil_orchestrator/tasks.py", line 78, in submit_jobs_to_lsf
    job = Job.objects.get(id=job_id)
  File "/juno/work/ci/prod_ridgeback/venv/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/juno/work/ci/prod_ridgeback/venv/lib/python3.7/site-packages/django/db/models/query.py", line 402, in get
    num = len(clone)
  File "/juno/work/ci/prod_ridgeback/venv/lib/python3.7/site-packages/django/db/models/query.py", line 256, in __len__
    self._fetch_all()
  File "/juno/work/ci/prod_ridgeback/venv/lib/python3.7/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/juno/work/ci/prod_ridgeback/venv/lib/python3.7/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/juno/work/ci/prod_ridgeback/venv/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1138, in execute_sql
    cursor = self.connection.cursor()
  File "/juno/work/ci/prod_ridgeback/venv/lib/python3.7/site-packages/django/db/backends/base/base.py", line 256, in cursor
    return self._cursor()
  File "/juno/work/ci/prod_ridgeback/venv/lib/python3.7/site-packages/django/db/backends/base/base.py", line 233, in _cursor
    self.ensure_connection()
  File "/juno/work/ci/prod_ridgeback/venv/lib/python3.7/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/juno/work/ci/prod_ridgeback/venv/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/juno/work/ci/prod_ridgeback/venv/lib/python3.7/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/juno/work/ci/prod_ridgeback/venv/lib/python3.7/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/juno/work/ci/prod_ridgeback/venv/lib/python3.7/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/juno/work/ci/prod_ridgeback/venv/lib/python3.7/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: FATAL:  remaining connection slots are reserved for non-replication superuser connections
```

**Comment by aef-** [comment]
One quick fix is to maybe set CONN_MAX_AGE to Postgres DB settings. This keeps all the DB connections open and celery can then reuse them as opposed to constantly opening and closing them.

https://github.com/celery/celery/pull/4292

**Comment by sivkovic** [comment]
Will do it with the next deploy. Production will be migrated to voyager machine since our deploy became a little bit messy, so it will be easier to test it with new configuration.
