### ISSUE TITLE
file_system tests fail

### ISSUE THREAD

**Issue by stevekm** [mskcc/beagle#92]
When running `python manage.py test`, a lot of LDAP errors are returned from the tests for the `file_system` app and result in test failure. 

https://github.com/mskcc/beagle/blob/develop/file_system/tests.py

```
Authentication failed for username: user DN/password rejected by LDAP server.

ERROR: test_create_file_invalid_file_group (file_system.tests.FileTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/kellys5/projects/beagle-dev/beagle-dev2/file_system/tests.py", line 118, in test_create_file_invalid_file_group
    self.client.credentials(HTTP_AUTHORIZATION='JWT %s' % self._generate_jwt())
  File "/Users/kellys5/projects/beagle-dev/beagle-dev2/file_system/tests.py", line 56, in _generate_jwt
    return response.data['token']
KeyError: 'token'
```

**Comment by allanbolipata** [comment]
@stevekm what is the status of this?

**Comment by stevekm** [comment]
@sivkovic I think you mentioned you might have fixed this one?
